name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Git Version
      id: version
      uses: codacy/git-version@2.7.1
      with:
        release-branch: main
    - name: Install pre-reqs
      run: cargo install cross
    - name: Build linux
      run: cross build --verbose --release --target x86_64-unknown-linux-gnu
    - name: Build windows
      run: cross build --verbose --release --target x86_64-pc-windows-gnu
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: packages
        path: |
          target/x86_64-unknown-linux-gnu/release/*.d
          target/x86_64-unknown-linux-gnu/release/*.so
          target/x86_64-pc-windows-gnu/release/*.d
          target/x86_64-pc-windows-gnu/release/*.dll
          target/x86_64-pc-windows-gnu/release/*.pdb
