name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Git Version
      id: version
      uses: codacy/git-version@2.7.1
      with:
        release-branch: main
    - name: Install pre-reqs
      run: sudo apt install libdbus-glib-1-dev
    - name: Build
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose
